from torch.utils.data import DataLoader
import dataloader_direct as dataloader
from direct_models import *
import torch
import numpy as np
from torch.optim.lr_scheduler import StepLR, ReduceLROnPlateau
from torch import nn
from torch.nn import functional as F
import os
import shutil
import json
import matplotlib.pyplot as plt
import time

from torch.utils.tensorboard import SummaryWriter

import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')


# config = json.load(open('/home/grzegorc/AWACA/Retrieval/DeepSpectralRetrieval-main/direct_retrieval/config.json'))
config = json.load(open('/home/grzegorc/AWACA/Retrieval/DeepSpectralRetrieval-main/direct_retrieval/config_cpu.json'))

directory = config['directory']


## Set-up tensorboard writer
writer = SummaryWriter(log_dir=directory)


## Prepare dataset
train_dataset = dataloader.direct_dataset(config['target_array'], config['spectrum_h5'],
                                           i_start_ds = config['i_start_ds'], i_end_ds = config['i_end_ds'],
                                           mean_normalization_json = config['mean_normalization_json'],
                                           std_normalization_json = config['std_normalization_json'],
                                           mean_normalization_npy = config['mean_normalization_npy'],
                                           std_normalization_npy = config['std_normalization_npy'],
                                           normalize_spectra = config['normalize_spectra'],
                                           normalize_target = config['normalize_target'])

val_dataset = dataloader.direct_dataset(config['target_array'], config['spectrum_h5'],
                                           i_start_ds = config['i_start_val_ds'], i_end_ds = config['i_end_val_ds'],
                                           mean_normalization_json = config['mean_normalization_json'],
                                           std_normalization_json = config['std_normalization_json'],
                                           mean_normalization_npy = config['mean_normalization_npy'],
                                           std_normalization_npy = config['std_normalization_npy'],
                                           normalize_spectra = config['normalize_spectra'],
                                            normalize_target = config['normalize_target'])

print('test',len(val_dataset),val_dataset)

### checks of nan of inf values (generated by claude)
# ## --- Check target array ---
# targets = np.load(config['target_array'])
# print('targets shape:', targets.shape)
# print('targets has NaN:', np.any(np.isnan(targets)))
# print('targets has Inf:', np.any(np.isinf(targets)))
#
# ## --- Check spectra (raw, from HDF5) ---
# spec_w = train_dataset.spectrum_W[:]
# spec_ka = train_dataset.spectrum_Ka[:]
# print('spectrum_W has NaN:', np.any(np.isnan(spec_w)), 'has Inf:', np.any(np.isinf(spec_w)))
# print('spectrum_Ka has NaN:', np.any(np.isnan(spec_ka)), 'has Inf:', np.any(np.isinf(spec_ka)))
#
# ## --- Check normalization stats ---
# target_mean = np.load(config['mean_normalization_npy'])
# target_std = np.load(config['std_normalization_npy'])
# print('target_mean has NaN:', np.any(np.isnan(target_mean)), 'has zero:', np.any(target_mean == 0))
# print('target_std has NaN:', np.any(np.isnan(target_std)), 'has zero:', np.any(target_std == 0))
#
# import json
# mean_json = json.load(open(config['mean_normalization_json']))
# std_json = json.load(open(config['std_normalization_json']))
# print('spectrum mean/std (W):', mean_json['spectrum_W_256'], std_json['spectrum_W_256'])
# print('spectrum mean/std (Ka):', mean_json['spectrum_Ka_256'], std_json['spectrum_Ka_256'])
#
# ## --- Check target array ---
# targets = np.load(config['target_array'])
# print('targets shape:', targets.shape)
# print('targets has NaN:', np.any(np.isnan(targets)))
# print('targets has Inf:', np.any(np.isinf(targets)))
#
# ## --- Check spectra (raw, from HDF5) ---
# spec_w = train_dataset.spectrum_W[:]
# spec_ka = train_dataset.spectrum_Ka[:]
# print('spectrum_W has NaN:', np.any(np.isnan(spec_w)), 'has Inf:', np.any(np.isinf(spec_w)))
# print('spectrum_Ka has NaN:', np.any(np.isnan(spec_ka)), 'has Inf:', np.any(np.isinf(spec_ka)))
#
# ## --- Check normalization stats ---
# target_mean = np.load(config['mean_normalization_npy'])
# target_std = np.load(config['std_normalization_npy'])
# print('target_mean has NaN:', np.any(np.isnan(target_mean)), 'has zero:', np.any(target_mean == 0))
# print('target_std has NaN:', np.any(np.isnan(target_std)), 'has zero:', np.any(target_std == 0))
#
# import json
# mean_json = json.load(open(config['mean_normalization_json']))
# std_json = json.load(open(config['std_normalization_json']))
# print('spectrum mean/std (W):', mean_json['spectrum_W_256'], std_json['spectrum_W_256'])
# print('spectrum mean/std (Ka):', mean_json['spectrum_Ka_256'], std_json['spectrum_Ka_256'])
#
#


























use_subsampler = config['use_subsampler']
with_wind=config['with_wind']

## Training parameters
nb_epochs = config['nb_epochs']
batch_size = config['batch_size']
val_batch_size = config['val_batch_size']
lr_initial = config['learning_rate_ini']

model_name = config['model_name']
n_channels = config['n_channels']

use_scheduler = config['scheduler']
if use_scheduler == 'step':
    lr_sched_step = config['lr_sched_step']
    lr_sched_gamma = config['lr_sched_gamma']
elif use_scheduler == 'plateau':
    lr_factor = config['lr_factor']
    lr_patience = config['lr_patience']
    lr_threshold = config['lr_threshold']
    lr_min = config['lr_min']

checkpoint_name = directory+config['checkpoint_name']

ts_size_per_epoch = 100000#config['ts_size_per_epoch']
num_workers_loader = config['num_workers_loader']



## Set-up model, optimizer and scheduler
device = config['device']
model = locals()[model_name](n_channels).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=lr_initial)
if use_scheduler=='step':
    scheduler = StepLR(optimizer, step_size=lr_sched_step, gamma=lr_sched_gamma)
elif use_scheduler=='plateau':
    scheduler = ReduceLROnPlateau(optimizer, factor = lr_factor, patience = lr_patience, threshold = lr_threshold, min_lr = lr_min)
stop_decreasing_after = config['stop_decreasing_after']

init = config['init']
if init=='xavier_normal':
    def weights_init(m):
        if isinstance(m, nn.Conv1d):
            torch.nn.init.xavier_normal_(m.weight)
            torch.nn.init.zeros_(m.bias)
        if isinstance(m, nn.Linear):
            torch.nn.init.xavier_normal_(m.weight)
            torch.nn.init.zeros_(m.bias)
    model.apply(weights_init)


## Load the checkpoint if it exists
bc = 0
nb_epochs_finished = 0
N = train_dataset.spectrum_W.shape[0]
epoch_loss_previous = 0
try:
    checkpoint = torch.load(checkpoint_name)
    nb_epochs_finished = checkpoint['nb_epochs_finished']
    bc = checkpoint['nb_batches_finished']
    model.load_state_dict(checkpoint['model_state'])
    optimizer.load_state_dict(checkpoint['optimizer_state'])
    if (use_scheduler=='step') & (nb_epochs_finished<=stop_decreasing_after):
        scheduler.load_state_dict(checkpoint['scheduler_state'])
    print(f'Checkpoint loaded with {nb_epochs_finished} epochs finished.')
except FileNotFoundError:
    print('Starting from scratch.')
except Exception as e:
    print('Error when loading the checkpoint: ', e)
    exit(1)




## Perform the training
# The validation dataloader is defined before training
val_dataloader = DataLoader(val_dataset, num_workers=num_workers_loader, batch_size=val_batch_size, pin_memory=True)

# If we don't use the subsampler, the dataloader is defined once and for all
if not(use_subsampler):
    train_dataloader = DataLoader(train_dataset, num_workers=num_workers_loader, batch_size=batch_size,pin_memory=True)



for epoch in range(nb_epochs_finished,nb_epochs):
    epochloss = 0

    if use_subsampler:
        inds = torch.arange((ts_size_per_epoch*epoch)%N, min(N,(ts_size_per_epoch*epoch)%N + ts_size_per_epoch))
        train_dataloader = DataLoader(train_dataset, num_workers=num_workers_loader, batch_size=batch_size, sampler = torch.utils.data.SubsetRandomSampler(inds), pin_memory=True)
        print(len(train_dataloader))

    for (input_data, target) in iter(train_dataloader):
        input_data = input_data.to(device)
        target = target.to(device)
        output = model(input_data)
        loss = 0.5 * ((output[:,0,:] - target).pow(2).sum())/ output.size(0)


        epochloss+=loss*output.size(0)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if bc%5==0:
            print(epoch,bc,loss)
            # print(bc,loss)
        bc+=1


    epoch_loss_previous = epochloss/ts_size_per_epoch
